version: "3.7"
services:
  web:
    build:
      context: .
    env_file: .env
    networks:
      - dev
    container_name: cinema_web
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    container_name: "cinema_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
    env_file:
      - .env
    
  redis:
    image: redis:latest
    container_name: cinema_redis
    networks:
      - dev
    restart: always
    env_file: .env
    ports:
      - "6379:6379"
    depends_on:
      - db


volumes:
  postgres_data:
  pgdata:

networks:
  dev: