version: '3.9'

services:
  web:
   build:
    context: .
   env_file: .env
   container_name: cinema_web   
   ports:
     - 8000:8000
   volumes:
     - .:/app
   command:  bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
   depends_on:
    - db

  db:
   image: postgres
   env_file: .env
   command: -p 5432
   expose:
    - 5432