version: "3.7"
services:
  web:
    build:
      context: .
    env_file: .env
    container_name: cinema_web
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db

  db:
    image: postgres:15.5-alpine3.19
    container_name: cinema_db
    restart: always
    env_file: .env
    command: -p 5432
    expose:
      - 5432
    
  redis:
    image: redis:latest
    container_name: cinema_redis
    restart: always
    env_file: .env
    ports:
      - "6379:6379"
    depends_on:
      - db

