"""create tag model 

Revision ID: 25adda59e2dc
Revises: a99de9cf3843
Create Date: 2024-06-08 10:17:14.416985

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25adda59e2dc"
down_revision: Union[str, None] = "a99de9cf3843"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "movies_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id", "movie_id", "id"),
    )
    op.drop_constraint("comments_movie_id_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        None, "comments", "movies", ["movie_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_movie_id_fkey", "comments", "movies", ["movie_id"], ["id"]
    )
    op.drop_table("movies_tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
