"""add unique const

Revision ID: 8c22285524ef
Revises: 8bf51a25430e
Create Date: 2024-07-10 09:01:32.003666

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c22285524ef'
down_revision: Union[str, None] = '8bf51a25430e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('mov_rat_1', 'movies_rating', ['movie_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mov_rat_1', 'movies_rating', type_='unique')
    # ### end Alembic commands ###
