"""init commit

Revision ID: bd2ea757dc50
Revises: 
Create Date: 2024-05-06 13:56:09.247988

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd2ea757dc50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_country_id_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_country_id_fkey', 'movies', 'actors', ['country_id'], ['id'])
    # ### end Alembic commands ###
