"""add slug and is_publish columns

Revision ID: f147447a8cec
Revises: b7ffe0f33e5f
Create Date: 2024-05-07 20:48:38.188291

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f147447a8cec'
down_revision: Union[str, None] = 'b7ffe0f33e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('movies', sa.Column('is_publish', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'movies', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('movies', 'is_publish')
    op.drop_column('movies', 'slug')
    # ### end Alembic commands ###
